### PR TITLE
Failfast for explicit error http request instead of retrying (#296)

### PR DESCRIPTION
**Pull request by larry4xie**
#296 

- Failfast http status code: 400, 401, 404, 405
- Error Code Description: https://www.apolloconfig.com/#/en/usage/other-language-client-user-guide?id=_16-error-code-description

### CODE REVIEW

**Comment by nobodyiam** [comment]
Fantastic work! Could we incorporate some unit tests to ensure coverage of the newly implemented logic?

**Comment by larry4xie** [comment]
@nobodyiam Unit tests 已提交（module protocol/http coverage: 61.4% > 69.3%）

image

**Comment by nobodyiam** [comment]
Looks like we need to also fix other test cases.

image

**Comment by larry4xie** [comment]
@nobodyiam fixed, and successfully ran all test cases

image

**Review by nobodyiam — APPROVED** [review]
LGTM

**Pull request merged**
