### PR TITLE
fix: 触发懒加载时，需要同步更新notify内容，更新component监听变更的ns

### PR DESCRIPTION
**Pull request by qdsordinarydream**
触发懒加载时，需要同步更新notify内容，更新component监听变更的ns；因为sync也会触发component返回，所以component不需要重新 start，期间两秒的时间足够configComponent变更appconfig

component 依赖 appconfig 的内容更新
image
image
image

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved the logic for configuration retrieval and caching in the application.
- **Tests**
	- Enhanced testing for configuration updates and notifications.
- **Refactor**
	- Code refactoring for better readability and efficiency in configuration management.

### CODE REVIEW

**Comment by nobodyiam** [comment]
Could you assist in including a test case that this pull request resolves?

**Comment by qdsordinarydream** [comment]
> Could you assist in including a test case that this pull request resolves?

sure, completed

**Comment by nobodyiam** [comment]
> > Could you assist in including a test case that this pull request resolves?
> 
> sure, completed

Thank you! Could you also assist in addressing the concerns mentioned by @coderabbitai?

**Review by zouyx — APPROVED** [review]

**Comment by zouyx** [comment]
I need more time to test this feature before release.

**Pull request merged**
