### PR TITLE
add get yaml

### PR DESCRIPTION
**Pull request by weihubeats**
https://github.com/apolloconfig/agollo/issues/306

## Summary by CodeRabbit

- **New Features**
  - Introduced functionality to convert properties to YAML format and vice versa.

- **Tests**
  - Added unit tests to validate property mapping, value parsing, and YAML generation functionalities.

### CODE REVIEW

**Comment by weihubeats** [comment]
Can anyone review this pr?

**Comment by nobodyiam** [comment]
@weihubeats would you please help to add some unit tests for this new feature?

**Comment by weihubeats** [comment]
add unit tests completed

**Comment by nobodyiam** [comment]
Upon reviewing feature request #306, it appears that the original intention was to support these namespaces in YAML format rather than transforming properties into YAML format, e.g.

screenshot

For reference, a similar feature has been implemented in the Java SDK as demonstrated below:

```java
Config config = ConfigService.getConfig("application.yml");
String someKey = "someKeyFromYmlNamespace";
String someDefaultValue = "someDefaultValueForTheKey";
String value = config.getProperty(someKey, someDefaultValue);
```

**Comment by qq2161811** [comment]
这个还没合并吗？急需要用T_T

**Pull request closed without merging**
